kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: python
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: parksmap
  Url:
  - Name: parksmap
    Port: 8080
